"""patch_libs.py — assemble the Arduboy libraries for NucleoOS into <gen>/ab2 and <gen>/ab1.

    python3 ports/arduboy/patch_libs.py <src dir (ports/_src/arduboy)> <gen dir>

ab2 = Arduboy2 (MLXXXp, BSD-3-Clause) at the commit pinned in fetch.sh: its portable drawing code
      (Arduboy2.cpp/.h, Arduboy2Data.cpp, SpritesB, Sprites) is used as-is except for three AVR
      assembly blocks, replaced by their plain C equivalents, and the boot logo, which is skipped.
      The hardware layer (Arduboy2Core, Arduboy2Audio, Arduboy2Beep) comes from shim/ab2.
      ArduboyTonesPitches.h (MIT) is copied from the pinned ArduboyTones.
ab1 = Arduboy 1.1.1 (Arduboy LLC, BSD-3-Clause) for older sketches: Arduboy.cpp/.h, glcdfont.c,
      ab_logo.c with the fillScreen assembly replaced, the ADC seed read replaced and the boot logo
      skipped; the core and audio come from shim/ab1.
Each patch asserts that its target text exists, so a changed upstream fails loudly.
"""
import os
import re
import shutil
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SHIM = os.path.join(HERE, "shim")


def replace_function(src, signature, body):
    """Replace the function whose definition starts with `signature` (at line start) by
    signature + body. Braces are matched from the first '{' after the signature."""
    m = re.search(r"^" + re.escape(signature) + r"\s*\([^)]*\)\s*\{", src, re.M)
    if not m:
        raise SystemExit(f"patch_libs: '{signature}' not found")
    start = m.start()
    i = m.end()
    depth = 1
    while depth:
        c = src[i]
        if c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
        i += 1
    head = src[start:m.end() - 1]
    return src[:start] + head + "{\n" + body + "\n}" + src[i:]


def must_sub(pattern, repl, src, count=1):
    new, n = re.subn(pattern, repl, src, count=count, flags=re.M | re.S)
    if n == 0:
        raise SystemExit(f"patch_libs: pattern not found: {pattern[:60]}")
    return new


def ab2(src, out):
    lib = os.path.join(src, "Arduboy2", "src")
    os.makedirs(out, exist_ok=True)
    for f in ("Arduboy2.h", "Arduboy2.cpp", "Arduboy2Data.cpp", "Sprites.h", "SpritesB.h", "SpritesB.cpp",
              "SpritesCommon.h"):
        shutil.copy(os.path.join(lib, f), os.path.join(out, f))
    shutil.copy(os.path.join(src, "Arduboy2", "LICENSE.txt"), os.path.join(out, "LICENSE-Arduboy2.txt"))
    # Sprites = SpritesB (the C implementation of the same class), under the Sprites name
    s = open(os.path.join(lib, "SpritesB.cpp"), encoding="utf-8").read()
    s = s.replace("SpritesB", "Sprites")
    open(os.path.join(out, "Sprites.cpp"), "w", encoding="utf-8").write(
        "// Generated by ports/arduboy/patch_libs.py from SpritesB.cpp (Arduboy2, BSD-3-Clause):\n"
        "// the plain C implementation replaces the AVR assembly of Sprites.cpp.\n" + s)
    p = os.path.join(out, "Arduboy2.cpp")
    s = open(p, encoding="utf-8").read()
    # drawPixel: the asm version, then an `#if 0` C reference copy; keep only a C version
    s = must_sub(r"#if 0\n// For reference, this is the C\+\+ equivalent\n.*?#endif\n", "", s)
    s = replace_function(s, "void Arduboy2Base::drawPixel", """
  if (x < 0 || x > (WIDTH-1) || y < 0 || y > (HEIGHT-1)) return;
  const uint16_t row_offset = (uint16_t)((y / 8) * WIDTH + x);
  const uint8_t bit = (uint8_t)(1 << (y & 7));
  uint8_t data = sBuffer[row_offset] | bit;
  if (!(color & _BV(0))) data ^= bit;
  sBuffer[row_offset] = data;""")
    s = replace_function(s, "void Arduboy2Base::fillScreen", """
  memset(sBuffer, color != BLACK ? 0xFF : 0x00, WIDTH * HEIGHT / 8);""")
    s = replace_function(s, "bool Arduboy2Base::readShowBootLogoFlag", """
  return false;   // NucleoOS: no boot logo""")
    if "asm" in re.sub(r"//.*", "", s):
        raise SystemExit("patch_libs: assembly left in Arduboy2.cpp")
    open(p, "w", encoding="utf-8").write("// Patched for NucleoOS by ports/arduboy/patch_libs.py\n" + s)
    tones = os.path.join(src, "ArduboyTones", "src", "ArduboyTonesPitches.h")
    shutil.copy(tones, os.path.join(out, "ArduboyTonesPitches.h"))
    shutil.copy(os.path.join(src, "ArduboyTones", "LICENSE.txt"), os.path.join(out, "LICENSE-ArduboyTones.txt"))
    for f in os.listdir(os.path.join(SHIM, "ab2")):
        shutil.copy(os.path.join(SHIM, "ab2", f), os.path.join(out, f))


def ab1(src, out):
    lib = os.path.join(src, "Arduboy", "src")
    os.makedirs(os.path.join(out, "core"), exist_ok=True)
    os.makedirs(os.path.join(out, "audio"), exist_ok=True)
    for f in ("Arduboy.h", "Arduboy.cpp", "glcdfont.c", "ab_logo.c"):
        shutil.copy(os.path.join(lib, f), os.path.join(out, f))
    shutil.copy(os.path.join(src, "Arduboy", "LICENSE"), os.path.join(out, "LICENSE-Arduboy.txt"))
    p = os.path.join(out, "Arduboy.cpp")
    s = open(p, encoding="utf-8").read()
    s = replace_function(s, "void Arduboy::fillScreen", """
  memset(sBuffer, color ? 0xFF : 0x00, WIDTH * HEIGHT / 8);""")
    s = replace_function(s, "uint16_t Arduboy::rawADC", """
  (void)adc_bits;
  return (uint16_t)(random(1024));""")
    s = replace_function(s, "void Arduboy::bootLogo", """
  // NucleoOS: no boot logo""")
    # write() falls off its end without a return value (undefined; Print::write(buf, n) stops early)
    s = replace_function(s, "size_t Arduboy::write", """
  if (c == '\\n')
  {
    cursor_y += textsize*8;
    cursor_x = 0;
  }
  else if (c == '\\r')
  {
  }
  else
  {
    drawChar(cursor_x, cursor_y, c, 1, 0, textsize);
    cursor_x += textsize*6;
    if (wrap && (cursor_x > (WIDTH - textsize*6)))
    {
      write('\\n');
    }
  }
  return 1;""")
    s = replace_function(s, "void Arduboy::initRandomSeed", """
  randomSeed((unsigned long)micros() ^ (unsigned long)random(0x7fffffffL) ^ 0x5eedUL);""")
    if "asm" in re.sub(r"//.*", "", s):
        raise SystemExit("patch_libs: assembly left in Arduboy.cpp")
    open(p, "w", encoding="utf-8").write("// Patched for NucleoOS by ports/arduboy/patch_libs.py\n" + s)
    shutil.copy(os.path.join(SHIM, "ab1", "core", "core.h"), os.path.join(out, "core", "core.h"))
    shutil.copy(os.path.join(SHIM, "ab1", "core", "core.cpp"), os.path.join(out, "core", "core.cpp"))
    shutil.copy(os.path.join(SHIM, "ab1", "audio", "audio.h"), os.path.join(out, "audio", "audio.h"))
    shutil.copy(os.path.join(SHIM, "ab1", "audio", "audio.cpp"), os.path.join(out, "audio", "audio.cpp"))


def fixedpoints(src, out):
    """FixedPointsArduino (Apache-2.0): `static constexpr SFixed Epsilon = ...` inside SFixed itself
    (an incomplete type there) is accepted by gcc only; turn those into static const members
    defined after the class."""
    shutil.rmtree(out, ignore_errors=True)
    shutil.copytree(os.path.join(src, "FixedPoints", "src"), out)
    shutil.copy(os.path.join(src, "FixedPoints", "LICENCE"), os.path.join(out, "LICENCE-FixedPoints.txt"))
    # the random helpers are AVR-only upstream; wasi-libc has the same random()
    p = os.path.join(out, "FixedPoints", "Details.h")
    d = open(p, encoding="utf-8").read()
    guard = "#if !defined(__AVR__)\n#define FIXED_POINTS_NO_RANDOM\n#endif\n"
    if guard not in d:
        raise SystemExit("patch_libs: FixedPoints random guard not found")
    open(p, "w", encoding="utf-8", newline="\n").write(d.replace(guard, ""))
    for cls in ("SFixed", "UFixed"):
        p = os.path.join(out, "FixedPoints", cls + ".h")
        s = open(p, encoding="utf-8").read()
        defs = []

        def repl(m):
            defs.append((m.group(1), m.group(2)))
            return f"\tstatic const {cls} {m.group(1)};"
        s = re.sub(r"^\tstatic constexpr " + cls + r" (\w+) = (.*?);[ \t]*$", repl, s, flags=re.M)
        if not defs:
            raise SystemExit(f"patch_libs: no constexpr members in {cls}.h")
        open(p, "w", encoding="utf-8", newline="\n").write(s)
        p = os.path.join(out, "FixedPoints", cls + "MemberFunctions.h")
        s = open(p, encoding="utf-8").read()
        extra = "".join(f"template< unsigned Integer, unsigned Fraction >\n"
                        f"constexpr {cls}<Integer, Fraction> {cls}<Integer, Fraction>::{n} = {e};\n\n" for n, e in defs)
        i = s.rindex("FIXED_POINTS_END_NAMESPACE")
        s = s[:i] + "// NucleoOS (patch_libs.py): the constants, defined outside the class\n" + extra + s[i:]
        open(p, "w", encoding="utf-8", newline="\n").write(s)


def main():
    src, gen = sys.argv[1], sys.argv[2]
    ab2(src, os.path.join(gen, "ab2"))
    ab1(src, os.path.join(gen, "ab1"))
    fixedpoints(src, os.path.join(gen, "FixedPoints"))


if __name__ == "__main__":
    main()
