"""embed_init.py <init.scm> <out.h> — TinyScheme's init.scm as a C string (nv_scheme_main.c)."""
import sys

data = open(sys.argv[1], "rb").read()
with open(sys.argv[2], "w", newline="\n") as f:
    f.write("// generated by ports/cli/scheme/embed_init.py - do not edit\n")
    f.write(f"static const char nv_init_scm[{len(data) + 1}] = {{")
    f.write(",".join(str(b) for b in data))
    f.write(",0};\n")
