// nv_scheme_main.c — TinyScheme front end for the NucleoOS Terminal (WASI).
//
// TinyScheme's own main() loads init.scm from the current directory; store packages carry no
// data files, so init.scm is compiled in (scheme_init.h, generated by ports/cli/build.sh) and
// loaded from memory before anything else.
//   scheme                 interactive prompt (ts>)
//   scheme file.scm [a..]  runs a file; the arguments are in *args*
//   scheme -i file.scm     runs a file, then the prompt
//   scheme -e '(expr)'     evaluates an expression and prints nothing else
#include <stdio.h>
#include <string.h>

#include "scheme-private.h"
#include "scheme.h"
#include "scheme_init.h"   // static const char nv_init_scm[]

static void set_args(scheme *sc, char **argv, int n) {
    pointer args = sc->NIL;
    for (int i = n - 1; i >= 0; i--) args = cons(sc, mk_string(sc, argv[i]), args);
    scheme_define(sc, sc->global_env, mk_symbol(sc, "*args*"), args);
}

static int load_file(scheme *sc, const char *name) {
    FILE *f = fopen(name, "r");
    if (!f) {
        fprintf(stderr, "scheme: cannot open %s\n", name);
        return 66;
    }
    scheme_load_named_file(sc, f, name);
    fclose(f);
    return sc->retcode;
}

int main(int argc, char **argv) {
    scheme sc;
    if (!scheme_init(&sc)) {
        fprintf(stderr, "scheme: could not initialize\n");
        return 2;
    }
    scheme_set_input_port_file(&sc, stdin);
    scheme_set_output_port_file(&sc, stdout);
    scheme_load_string(&sc, nv_init_scm);
    scheme_load_string(&sc, "(define exit quit)");   // the R7RS name of TinyScheme's quit

    int rc = 0;
    if (argc >= 2 && (!strcmp(argv[1], "-h") || !strcmp(argv[1], "--help") || !strcmp(argv[1], "-?"))) {
        puts("usage: scheme                 interactive prompt\n"
             "       scheme file.scm [args]  run a file (arguments in *args*)\n"
             "       scheme -i file.scm      run a file, then the prompt\n"
             "       scheme -e '(expr)'      evaluate an expression");
    } else if (argc >= 3 && !strcmp(argv[1], "-e")) {
        set_args(&sc, argv + 3, argc - 3);
        scheme_load_string(&sc, argv[2]);
        rc = sc.retcode;
    } else if (argc >= 3 && !strcmp(argv[1], "-i")) {
        set_args(&sc, argv + 3, argc - 3);
        rc = load_file(&sc, argv[2]);
        scheme_load_named_file(&sc, stdin, 0);
        rc = sc.retcode;
    } else if (argc >= 2) {
        set_args(&sc, argv + 2, argc - 2);
        rc = load_file(&sc, argv[1]);
    } else {
        set_args(&sc, argv, 0);
        printf("TinyScheme 1.42 - type an expression; (exit) or EOF quits.\n");
        scheme_load_named_file(&sc, stdin, 0);
        rc = sc.retcode;
    }
    scheme_deinit(&sc);
    return rc;
}
