"""gen_font.py — the antialiased text font of the Puzzles app (pz_font.h).

    python ports/puzzles/gen_font.py <out/pz_font.h>

Rasterises printable ASCII (32..126) from Aileron Regular — the CC0 (public domain) typeface Pillow
embeds for ImageFont.load_default(size) — at PZF_SIZE px into a 4-bit alpha atlas. The app scales it
to whatever size a puzzle asks for (supersampled, cached per size), so one atlas serves every size.
"""
import sys

from PIL import Image, ImageDraw, ImageFont, features

SIZE = 72   # em size of the atlas; puzzles rarely ask for bigger text than this

if not features.check("freetype2"):
    sys.exit("gen_font.py: Pillow was built without FreeType (needed for the embedded Aileron font)")
font = ImageFont.load_default(SIZE)
if font.getname()[0] != "Aileron":
    sys.exit("gen_font.py: expected Pillow's embedded Aileron font, got %r" % (font.getname(),))

ascent, descent = font.getmetrics()
cap = -font.getbbox("H", anchor="ls")[1]
glyphs, data = [], bytearray()
for code in range(32, 127):
    ch = chr(code)
    adv = font.getlength(ch)
    x0, y0, x1, y1 = font.getbbox(ch, anchor="ls")
    w, h = max(0, x1 - x0), max(0, y1 - y0)
    if ch == " ":
        w = h = 0
    off = len(data)
    if w and h:
        img = Image.new("L", (w, h), 0)
        ImageDraw.Draw(img).text((-x0, -y0), ch, font=font, fill=255, anchor="ls")
        px = img.load()
        for y in range(h):
            row = [(px[x, y] + 8) // 17 for x in range(w)]   # 0..255 -> 0..15
            if w & 1:
                row.append(0)
            for x in range(0, len(row), 2):
                data.append(row[x] | (row[x + 1] << 4))
    assert -128 <= x0 <= 127 and -128 <= y0 <= 127 and w < 256 and h < 256
    glyphs.append((int(round(adv * 16)), x0, y0, w, h, off))

with open(sys.argv[1], "w") as f:
    f.write("// Generated by ports/puzzles/gen_font.py from Aileron Regular (CC0). Do not edit.\n")
    f.write("#define PZF_SIZE %d\n#define PZF_ASCENT %d\n#define PZF_DESCENT %d\n#define PZF_CAP %d\n"
            % (SIZE, ascent, descent, cap))
    f.write("static const struct { int16_t adv16; int8_t x0, y0; uint8_t w, h; uint32_t off; } "
            "pzf_glyphs[95] = {\n")
    for g in glyphs:
        f.write("    {%d, %d, %d, %d, %d, %d},\n" % g)
    f.write("};\nstatic const uint8_t pzf_data[%d] = {\n" % len(data))
    for i in range(0, len(data), 24):
        f.write("    " + ",".join(str(b) for b in data[i:i + 24]) + ",\n")
    f.write("};\n")
print("pz_font.h: %d glyphs, %d bytes of 4-bit alpha at %d px" % (len(glyphs), len(data), SIZE))
