"""gen_meta.py — the puzzle list of the combined build, read from upstream's CMakeLists.txt.

    python ports/puzzles/gen_meta.py <puzzles src dir> <out dir> [excluded ids...]

Writes <out>/generated-games.h (GAME(id) lines for list.c / puzzles.h COMBINED, sorted by display
name) and <out>/pz_meta.h (the same order: id, display name, one-line description, objective), and
prints the ids to compile, one per line.
"""
import os
import re
import sys

src, out, excluded = sys.argv[1], sys.argv[2], set(sys.argv[3:])
text = open(os.path.join(src, "CMakeLists.txt"), encoding="utf-8").read().replace("\\\n", "")

games = []
for m in re.finditer(r"^puzzle\((\w+)(.*?)\)\s*$", text, re.M | re.S):
    ident, body = m.group(1), m.group(2)
    if ident in excluded:
        continue
    field = lambda k: (re.search(k + r'\s+"([^"]*)"', body) or [None, ""])[1]
    games.append((field("DISPLAYNAME") or ident, ident, field("DESCRIPTION"), field("OBJECTIVE")))
games.sort(key=lambda g: g[0].lower())

cstr = lambda s: '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'
os.makedirs(out, exist_ok=True)
with open(os.path.join(out, "generated-games.h"), "w") as f:
    for g in games:
        f.write("GAME(%s)\n" % g[1])
with open(os.path.join(out, "pz_meta.h"), "w") as f:
    f.write("// Generated by ports/puzzles/gen_meta.py from upstream CMakeLists.txt. Do not edit.\n")
    f.write("static const struct { const char *id, *name, *desc, *objective; } pz_meta[] = {\n")
    for name, ident, desc, obj in games:
        f.write("    {%s, %s, %s, %s},\n" % (cstr(ident), cstr(name), cstr(desc), cstr(obj)))
    f.write("};\n")
for g in games:
    print(g[1])
