// nv_zork.c — Zork I, II, III in the NucleoOS Terminal.
//
// Interpreter: MojoZork by Ryan C. Gordon (zlib license), a Z-machine v3 in one C file, included
// unmodified below. Stories: Zork I-III as released by Microsoft under the MIT license (2025),
// historicalsource/zorkN COMPILED/zorkN.z3, embedded in the module (the store only ships images,
// sounds and models as separate files).
//
//   zork          menu          zork 2        Zork II straight away
//
// The only adaptation is fopen(): the story file name resolves to the embedded bytes (fmemopen)
// and MojoZork's single "save.dat" becomes one save per game in the app's data folder (manifest
// permission "fs" makes that folder the program's "/").
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

#include "zork_stories.h"   // generated by ports/build.sh: zork1_z3[], zork2_z3[], zork3_z3[]

static const char *g_save = "zork1.sav";

static FILE *nv_zork_fopen(const char *name, const char *mode)
{
    static const struct { const char *name; const unsigned char *data; unsigned len; } kStories[] = {
        {"zork1.z3", zork1_z3, sizeof zork1_z3},
        {"zork2.z3", zork2_z3, sizeof zork2_z3},
        {"zork3.z3", zork3_z3, sizeof zork3_z3},
    };
    for (unsigned i = 0; i < sizeof kStories / sizeof kStories[0]; i++)
        if (!strcmp(name, kStories[i].name))
            return fmemopen((void *)kStories[i].data, kStories[i].len, "rb");
    if (!strcmp(name, "save.dat")) return fopen(g_save, mode);
    return fopen(name, mode);
}

#define fopen(n, m) nv_zork_fopen((n), (m))
#define main mojozork_upstream_main
#include "mojozork.c"
#undef main
#undef fopen

int main(int argc, char **argv)
{
    static ZMachineState zmachine_state;
    int game = (argc >= 2) ? atoi(argv[1]) : 0;

    printf("ZORK I, II, III - Infocom (1980-82), (c) Microsoft, MIT license\n");
    printf("Interpreter: MojoZork (c) Ryan C. Gordon, zlib license\n\n");
    while (game < 1 || game > 3) {
        char line[16];
        printf("Which game? 1 = Zork I, 2 = Zork II, 3 = Zork III: ");
        fflush(stdout);
        if (!fgets(line, sizeof line, stdin)) return 0;
        game = atoi(line);
    }
    static char story[16], save[16];
    snprintf(story, sizeof story, "zork%d.z3", game);
    snprintf(save, sizeof save, "zork%d.sav", game);
    g_save = save;
    printf("Type SAVE / RESTORE to keep your progress, QUIT to leave.\n\n");

    GState = &zmachine_state;
    GState->startup_script = NULL;
    GState->die = die;
    GState->writestr = writestr_stdio;
    random_seed = (int) time(NULL);

    loadStory(story);
    while (!GState->quit) runInstruction();

    free(GState->story);
    free(GState->story_filename);
    return 0;
}
