"""gen.py — generate everything of the IF catalog that is not a binary, from games.json.

    python ports/ifgames/gen.py [slug ...]        (called by build.sh; default: every game)

For each game: ports/_src/ifgames_gen/<slug>.c (credits + #embed of the raw-deflated story, whole; a Blorb marked
"strip_blorb" keeps only its executable chunk, when its pictures would not fit and the licence allows it),
apps/if-<slug>/{manifest.json,GUIDE.md,GUIDE.en.md}.
Always rewrites ports/ifgames/GAMES.md and ports/ifgames/catalog_entries.json for the whole list.
Prints one line per selected game for build.sh: "slug interpreter label bg fg".
"""
import hashlib
import json
import os
import struct
import zlib
import sys

HERE = os.path.dirname(os.path.abspath(__file__)).replace("\\", "/")
PORTS = os.path.dirname(HERE)
ROOT = os.path.dirname(PORTS)
SRC = PORTS + "/_src/ifgames"
GEN = PORTS + "/_src/ifgames_gen"

FORMAT_NAMES = {"z3": "Z-machine v3", "z5": "Z-machine v5", "z8": "Z-machine v8",
                "zblorb": "Z-machine (Blorb)", "ulx": "Glulx", "gblorb": "Glulx (Blorb)"}
LANG_EN = {"en": "English", "it": "Italian"}
LANG_IT = {"en": "inglese", "it": "italiano"}
INTERP = {"frotz": ("Frotz 2.55", "GPL-2.0-or-later", "https://gitlab.com/DavidGriffith/frotz"),
          "glulxe": ("Glulxe + CheapGlk", "MIT", "https://github.com/erkyrath/glulxe")}


def c_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def blorb_exec(data, want):
    """The executable chunk (ZCOD / GLUL) of a Blorb file."""
    if data[:4] != b"FORM" or data[8:12] != b"IFRS":
        return data
    pos = 12
    while pos + 8 <= len(data):
        cid, ln = data[pos:pos + 4], struct.unpack(">I", data[pos + 4:pos + 8])[0]
        if cid == want:
            return data[pos + 8:pos + 8 + ln]
        pos += 8 + ln + (ln & 1)
    raise SystemExit(f"blorb without {want!r} chunk")


def story_bytes(g):
    path = f"{SRC}/{g['file']}"
    data = open(path, "rb").read()
    sha = hashlib.sha256(data).hexdigest()
    if sha != g["sha256"]:
        raise SystemExit(f"{g['slug']}: sha256 {sha} != games.json {g['sha256']}")
    fmt = g["format"]
    if g.get("strip_blorb"):   # only for licences that allow adaptations (never ND)
        assert "ND" not in g["license"]
        return (blorb_exec(data, b"GLUL"), "ulx") if fmt == "gblorb" else (blorb_exec(data, b"ZCOD"), "z")
    return data, fmt


def interp(g):
    return "glulxe" if g["format"] in ("ulx", "gblorb") else "frotz"


def write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)


def gen_c(g):
    data, ext = story_bytes(g)
    # Stored raw-deflated (inflated once at start by tinfl): about 3x smaller modules, and the
    # bigger games fit the 2 MB app.wasm cap.
    co = zlib.compressobj(9, zlib.DEFLATED, -15)
    packed = co.compress(data) + co.flush()
    story = f"{GEN}/{g['slug']}.story.deflate"
    if not os.path.exists(story) or open(story, "rb").read() != packed:
        open(story, "wb").write(packed)
    lic = g["license"] + (" (non-commercial)" if g.get("nc") else "")
    credit = f"by {g['author']} ({g['year']}) - {lic}"
    write(f"{GEN}/{g['slug']}.c",
          f"// generated by ports/ifgames/gen.py - {g['title']}\n"
          f"#define NV_IF_TITLE {c_str(g['title'])}\n"
          f"#define NV_IF_CREDIT {c_str(credit)}\n"
          f"#define NV_IF_STORY_NAME {c_str(g['slug'] + '.' + ext)}\n"
          f"#define NV_IF_STORY_SIZE {len(data)}u\n"
          f"#define NV_IF_{interp(g).upper()}\n"
          f"static const unsigned char nv_if_story_z[] = {{\n#embed {c_str(story)}\n}};\n"
          f"#include \"nv_if_main.c\"\n")


def descriptions(g):
    tip_en = f"Type if-{g['slug']} in the Terminal or tap the icon."
    tip_it = f"Scrivi if-{g['slug']} nel Terminale o tocca l'icona."
    nc_en = " Non-commercial licence." if g.get("nc") else ""
    nc_it = " Licenza non commerciale." if g.get("nc") else ""
    return {
        "en": f"{g['desc_en']} Text adventure in {LANG_EN[g['lang']]} ({g['author']}, {g['year']}).{nc_en} {tip_en}",
        "it": f"{g['desc_it']} Avventura testuale in {LANG_IT[g['lang']]} ({g['author']}, {g['year']}).{nc_it} {tip_it}",
    }


def manifest(g):
    name, ilic, _ = INTERP[interp(g)]
    d = descriptions(g)
    m = {
        "id": f"if-{g['slug']}",
        "name": g["title"],
        "version": "1.0",
        "abi": 8,
        "console": True,
        "ram_budget": 8388608 if interp(g) == "glulxe" else 4194304,
        "stack_kb": 256 if interp(g) == "glulxe" else 64,
        "permissions": ["fs"],
        "author": f"{g['author']}; interpreter: {name}",
        "license": f"{g['license']} (game), {ilic} (interpreter)",
        "source": g["source"],
        "description": d["en"],
        "descriptions": d,
    }
    return json.dumps(m, indent=2, ensure_ascii=False) + "\n"


GUIDE_IT = """# {title}

## Il gioco

{desc_it}

- **Autore:** {author} ({year})
- **Lingua del gioco:** {lang_it}
- **Formato:** {fmt}, interprete {iname}

## Come si gioca

È un'**avventura testuale** (interactive fiction): il gioco descrive dove sei, tu scrivi cosa fare
in frasi brevi, in {lang_it}, e premi Invio. Si comincia quasi sempre guardandosi intorno.

| Comando | Abbreviazione | Cosa fa |
|---|---|---|
{commands_it}

Consigli: esamina tutto (`EXAMINE` / `X`), prendi quello che puoi, prova le direzioni elencate nelle
descrizioni, e se ti blocchi rileggi la stanza con `LOOK`. Molti giochi capiscono `HELP` o `HINT`.
Con `UNDO` torni indietro di una mossa.

## Salvare la partita

`SAVE` chiede un nome di file (Invio accetta quello proposto) e lo scrive nella cartella dati
dell'app sulla SD (`/sdcard/apps/if-{slug}/data`). `RESTORE` lo ricarica, anche dopo aver chiuso
il Terminale. `QUIT` esce dal gioco.

## Nel Terminale

- **Tocca l'icona** per aprire il Terminale con il gioco già avviato, oppure apri **Terminale** e scrivi `if-{slug}`.
- Scrivi nella riga in basso e premi Invio: la riga va al gioco.
- **STOP** interrompe subito il gioco (senza salvare).

## Crediti e licenza

**{title}** © {author}, {year}. {license_line_it}
Testo della licenza: <{license_url}>
Fonte del gioco: <{source}>

{license_quote_block}

Interprete: **{iname}**, licenza {ilic} (<{iurl}>). {mod_it}
"""

GUIDE_EN = """# {title}

## The game

{desc_en}

- **Author:** {author} ({year})
- **Game language:** {lang_en}
- **Format:** {fmt}, {iname} interpreter

## How to play

This is a **text adventure** (interactive fiction): the game tells you where you are, you type what to
do in short sentences, in {lang_en}, and press Enter. Start by looking around.

| Command | Short | What it does |
|---|---|---|
{commands_en}

Tips: examine everything (`EXAMINE` / `X`), take what you can, try the exits the descriptions
mention, and if you are stuck read the room again with `LOOK`. Many games understand `HELP` or `HINT`.
`UNDO` takes back one move.

## Saving

`SAVE` asks for a file name (Enter accepts the suggested one) and writes it to the app's data folder
on the SD card (`/sdcard/apps/if-{slug}/data`). `RESTORE` loads it back, even after closing the
Terminal. `QUIT` leaves the game.

## In the Terminal

- **Tap the icon** to open the Terminal with the game already running, or open **Terminal** and type `if-{slug}`.
- Type in the bottom line and press Enter: the line goes to the game.
- **STOP** kills the game right away (without saving).

## Credits and licence

**{title}** © {author}, {year}. {license_line_en}
Licence text: <{license_url}>
Game source: <{source}>

{license_quote_block}

Interpreter: **{iname}**, {ilic} licence (<{iurl}>). {mod_en}
"""

CMDS_EN = [("LOOK", "L", "describe where you are"), ("INVENTORY", "I", "what you are carrying"),
           ("NORTH, SOUTH, EAST, WEST, UP, DOWN", "N S E W U D", "move (also NE, NW, SE, SW, IN, OUT)"),
           ("EXAMINE lamp", "X LAMP", "look closely at something"),
           ("TAKE lamp / DROP lamp", "GET", "pick up / put down"),
           ("OPEN door, PUSH button, TALK TO man", "", "act on things and people"),
           ("AGAIN", "G", "repeat the last command"), ("WAIT", "Z", "let time pass"),
           ("SAVE / RESTORE", "", "save / load the game"), ("UNDO", "", "take back one move"),
           ("QUIT", "Q", "leave the game")]
CMDS_IT_FOR_EN_GAME = [("LOOK", "L", "descrive dove sei"), ("INVENTORY", "I", "cosa porti con te"),
                       ("NORTH, SOUTH, EAST, WEST, UP, DOWN", "N S E W U D",
                        "ti sposti (anche NE, NW, SE, SW, IN, OUT)"),
                       ("EXAMINE lamp", "X LAMP", "guarda da vicino un oggetto"),
                       ("TAKE lamp / DROP lamp", "GET", "prendi / lascia"),
                       ("OPEN door, PUSH button, TALK TO man", "", "agisci su cose e persone"),
                       ("AGAIN", "G", "ripete l'ultimo comando"), ("WAIT", "Z", "lascia passare il tempo"),
                       ("SAVE / RESTORE", "", "salva / carica la partita"), ("UNDO", "", "annulla una mossa"),
                       ("QUIT", "Q", "esci dal gioco")]
CMDS_IT_GAME = [("GUARDA", "G / L", "descrive dove sei"), ("INVENTARIO", "I", "cosa porti con te"),
                ("NORD, SUD, EST, OVEST, SU, GIÙ", "N S E O ALTO BASSO", "ti sposti"),
                ("ESAMINA lampada", "X / ESA", "guarda da vicino un oggetto"),
                ("PRENDI lampada / LASCIA lampada", "", "prendi / lascia"),
                ("APRI porta, PARLA CON uomo", "", "agisci su cose e persone"),
                ("SALVA / CARICA", "SAVE / RESTORE", "salva / carica la partita"),
                ("FINE", "QUIT", "esci dal gioco")]
CMDS_EN_FOR_IT_GAME = [(a, b, c) for (a, b, _), (_, _, c) in zip(
    CMDS_IT_GAME, [("", "", "describe where you are"), ("", "", "what you are carrying"),
                   ("", "", "move"), ("", "", "look closely at something"), ("", "", "pick up / put down"),
                   ("", "", "act on things and people"), ("", "", "save / load the game"),
                   ("", "", "leave the game")])]


def table(rows):
    return "\n".join(f"| `{a}` | {('`' + b + '`') if b else ''} | {c} |" for a, b, c in rows)


def guides(g):
    iname, ilic, iurl = INTERP[interp(g)]
    italian = g["lang"] == "it"
    nc = g.get("nc") and "non-commercial" not in g["license"]
    quote = g.get("license_quote", "")
    f = dict(g, slug=g["slug"], lang_it=LANG_IT[g["lang"]], lang_en=LANG_EN[g["lang"]],
             fmt=FORMAT_NAMES[g["format"]], iname=iname, ilic=ilic, iurl=iurl,
             commands_it=table(CMDS_IT_GAME if italian else CMDS_IT_FOR_EN_GAME),
             commands_en=table(CMDS_EN_FOR_IT_GAME if italian else CMDS_EN),
             license_line_it=f"Licenza: **{g['license']}**" + (" (solo uso non commerciale)." if nc else "."),
             license_line_en=f"Licence: **{g['license']}**" + (" (non-commercial use only)." if nc else "."),
             mod_it=("Il file della storia è ridistribuito senza le immagini, che qui non si possono mostrare (resta il "
                     "codice di gioco), come la licenza consente; l'interprete è invariato." if g.get("strip_blorb") else
                     "Gioco e interprete sono ridistribuiti invariati; NucleoOS aggiunge solo l'avvio e l'accesso "
                     "al file della storia incorporato."),
             mod_en=("The story file is redistributed without its pictures (game code only; they cannot be shown "
                     "here), as the licence allows; the interpreter is unmodified." if g.get("strip_blorb") else
                     "Game and interpreter are redistributed unmodified; NucleoOS only adds the launcher and access "
                     "to the embedded story file."),
             license_quote_block=(f"> {quote}" if quote else ""))
    return GUIDE_IT.format(**f), GUIDE_EN.format(**f)


def games_md(games):
    out = ["# Interactive fiction catalog", "",
           "One Terminal app per game (`apps/if-<slug>/`), built by `build.sh` from `games.json`.",
           "Every licence below was checked at the URL given; the quote is the statement relied on.",
           "Interpreters: Frotz 2.55 dumb (z-code, GPL-2.0-or-later), Glulxe + CheapGlk (Glulx, MIT);",
           "the story is stored raw-deflated in the module and inflated at start with miniz tinfl (MIT).",
           "Rebuild: `bash ports/ifgames/build.sh`, test on the PC: `bash ports/ifgames/test.sh`.", "",
           "| App | Title | Author | Year | Format | Lang | Licence | Story sha256 |",
           "|---|---|---|---|---|---|---|---|"]
    for g in games:
        lic = g["license"] + (" **NC**" if g.get("nc") else "")
        out.append(f"| if-{g['slug']} | {g['title']} | {g['author']} | {g['year']} | {g['format']} | "
                   f"{g['lang']} | [{lic}]({g['license_url']}) | `{g['sha256']}` |")
    out += ["", "## Licence statements", ""]
    for g in games:
        src = f"{g['url']} ({g['member']})" if g.get("zip") else g["url"]
        note = f" Note: {g['note']}." if g.get("note") else ""
        out.append(f"- **{g['title']}** — {g['license']}, <{g['license_url']}>: "
                   f"\"{g.get('license_quote', '')}\" — story: <{src}>, IFDB: <{g['source']}>.{note}")
    try:
        rej = json.load(open(f"{HERE}/rejected.json", encoding="utf-8"))
    except FileNotFoundError:
        rej = []
    if rej:
        out += ["", "## Not included", "", "| Game | Author | Reason |", "|---|---|---|"]
        out += [f"| {r['title']} | {r['author']} | {r['reason']} |" for r in rej]
    write(f"{HERE}/GAMES.md", "\n".join(out) + "\n")


def catalog(games):
    cat = {}
    for g in games:
        d = descriptions(g)
        cat[f"if-{g['slug']}"] = {"category": "terminal", "featured": False, "rating": g.get("rating", 4.0),
                                  "regions": ["*"], "names": {"en": g["title"], "it": g["title"]},
                                  "descriptions": d}
    write(f"{HERE}/catalog_entries.json", json.dumps(cat, indent=2, ensure_ascii=False) + "\n")


def main():
    games = json.load(open(f"{HERE}/games.json", encoding="utf-8"))
    for g in games:
        assert len(f"if-{g['slug']}") <= 31 and all(c in "abcdefghijklmnopqrstuvwxyz0123456789-" for c in g["slug"])
    games_md(games)
    catalog(games)
    sel = [g for g in games if not sys.argv[1:] or g["slug"] in sys.argv[1:]]
    for g in sel:
        gen_c(g)
        d = f"{ROOT}/apps/if-{g['slug']}"
        write(f"{d}/manifest.json", manifest(g))
        it, en = guides(g)
        write(f"{d}/GUIDE.md", it)
        write(f"{d}/GUIDE.en.md", en)
        ic = g["icon"]
        print(g["slug"], interp(g), ic["label"].replace(" ", "_"), ic["bg"], ic["fg"])


if __name__ == "__main__":
    main()
