// miniz_export.h — normally generated by CMake's GenerateExportHeader module (miniz has no
// committed template for it); we build a single static binary, no shared-library visibility
// needed, so MINIZ_EXPORT is just empty.
#pragma once
#define MINIZ_EXPORT
