// nv_pad — every game controller the OS knows, as one standard pad per player.
//
// Drivers (USB HID in nv_hid_host, USB XInput in nv_xinput, Bluetooth LE HID in nv_bt) attach a
// slot when a controller connects, push its state on every input report and detach on disconnect.
// Consumers (games through the WASM ABI, WASM-4, the Settings controller tester, /api/pads) read
// the slots in connection order: index 0 is player 1.
//
// The standard layout is the SDL GameController / Xbox one: A B X Y (south, east, west, north),
// Back / Guide / Start, stick clicks, shoulders, D-pad, analog sticks and analog triggers. Generic
// HID pads report raw buttons and axes whose meaning differs per model; nv_pad_map_* turns them
// into the standard layout with the SDL_GameControllerDB mappings compiled into the firmware
// (nv_paddb.c, generated by tools/gen_paddb.py) plus optional user lines in /sdcard/data/pads.txt
// (same text format as gamecontrollerdb.txt), with a heuristic for pads nobody has mapped.
#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define NV_PAD_MAX 4

// Standard buttons (bit numbers follow SDL_GameControllerButton, then the two digital triggers).
enum {
    NV_PADB_A        = 1u << 0,    // south (Xbox A, PlayStation Cross, Nintendo B position)
    NV_PADB_B        = 1u << 1,    // east
    NV_PADB_X        = 1u << 2,    // west
    NV_PADB_Y        = 1u << 3,    // north
    NV_PADB_BACK     = 1u << 4,    // View / Select / Share
    NV_PADB_GUIDE    = 1u << 5,    // Xbox / PS / Home
    NV_PADB_START    = 1u << 6,    // Menu / Options / Start
    NV_PADB_LSTICK   = 1u << 7,
    NV_PADB_RSTICK   = 1u << 8,
    NV_PADB_LB       = 1u << 9,
    NV_PADB_RB       = 1u << 10,
    NV_PADB_UP       = 1u << 11,
    NV_PADB_DOWN     = 1u << 12,
    NV_PADB_LEFT     = 1u << 13,
    NV_PADB_RIGHT    = 1u << 14,
    NV_PADB_MISC     = 1u << 15,   // Share (Series X), Capture (Switch), Mute (DualSense)
    NV_PADB_PADDLE1  = 1u << 16,
    NV_PADB_PADDLE2  = 1u << 17,
    NV_PADB_PADDLE3  = 1u << 18,
    NV_PADB_PADDLE4  = 1u << 19,
    NV_PADB_TOUCHPAD = 1u << 20,
    NV_PADB_LT       = 1u << 21,   // left trigger past ~50% (also set by digital-only triggers)
    NV_PADB_RT       = 1u << 22,
};
#define NV_PAD_N_BUTTONS 23

// Axes: sticks -32768..32767 (x right, y DOWN, like SDL), triggers 0..32767.
enum { NV_PADA_LX = 0, NV_PADA_LY, NV_PADA_RX, NV_PADA_RY, NV_PADA_LT, NV_PADA_RT, NV_PAD_N_AXES };

typedef struct {
    uint32_t buttons;               // NV_PADB_*
    int16_t  axis[NV_PAD_N_AXES];   // NV_PADA_*
} nv_pad_input_t;

typedef enum {
    NV_PAD_SRC_NONE = 0,
    NV_PAD_SRC_USB_HID = 1,         // generic USB HID gamepad / joystick
    NV_PAD_SRC_XINPUT = 2,          // USB Xbox 360 / One / Series (vendor protocol)
    NV_PAD_SRC_BLE = 3,             // Bluetooth LE HID (HOGP)
} nv_pad_source_t;

typedef struct {
    uint8_t  source;                // nv_pad_source_t
    uint8_t  mapped;                // 1 = mapping from the DB / pads.txt / native protocol, 0 = guessed
    uint8_t  battery;               // 0..100, 255 = unknown / wired
    uint8_t  rumble;                // 1 = nv_pad_rumble works on it
    uint16_t vid, pid;
    char     name[40];
} nv_pad_info_t;

// ---- driver side -------------------------------------------------------------------------------

// Rumble hook a driver may register for its slot: strengths 0..65535, called from the caller's
// task (keep it short / non-blocking).
typedef bool (*nv_pad_rumble_fn)(void *ctx, uint16_t low, uint16_t high);

// Claim a slot for a newly connected controller. Returns a slot id (>= 0) or -1 when all
// NV_PAD_MAX are taken. The state starts neutral.
int  nv_pad_attach(const nv_pad_info_t *info);
void nv_pad_set_rumble(int slot, nv_pad_rumble_fn fn, void *ctx);
void nv_pad_set_battery(int slot, uint8_t percent);
// New state for a slot (derives NV_PADB_LT/RT from the analog triggers when the driver didn't).
void nv_pad_update(int slot, const nv_pad_input_t *in);
void nv_pad_detach(int slot);

// ---- consumer side -----------------------------------------------------------------------------

// Connected controllers, numbered in connection order (a disconnect closes the gap).
int  nv_pad_count(void);
// State and/or info of the index-th controller (either pointer may be NULL). False = no such pad.
bool nv_pad_get(int index, nv_pad_input_t *in, nv_pad_info_t *info);
// Rumble the index-th controller for `ms` (0 = stop). False when it can't rumble.
bool nv_pad_rumble(int index, uint16_t low, uint16_t high, uint32_t ms);
// Incremented on every attach / detach (UI can poll it cheaply).
uint32_t nv_pad_generation(void);

// D-pad OR left stick past ~40% as NV_PADB_UP/DOWN/LEFT/RIGHT bits (menus and 8-way games).
uint32_t nv_pad_dirs(const nv_pad_input_t *in);

// ---- generic HID -> standard mapping (used by the USB HID and BLE HID drivers) -------------------

// Raw state of a HID pad in "joystick" terms, the way SDL enumerates it: axes ordered by their
// Linux ABS code (X, Y, Z, Rx, Ry, Rz, Slider, Dial, Wheel, Accelerator, Brake ...), normalised to
// -32768..32767; hats as SDL hat masks (1 up, 2 right, 4 down, 8 left, 0 centred); buttons by
// rank of their HID usage (button 1 = bit 0).
#define NV_HID_MAX_AXES 12
#define NV_HID_MAX_HATS 2
typedef struct {
    int16_t  axis[NV_HID_MAX_AXES];
    uint8_t  hat[NV_HID_MAX_HATS];
    uint64_t buttons;
} nv_hid_raw_t;

// One source per standard target: 0xFF none; else
//   00bbbbbb  button b (0..63)
//   01mmaaaa  axis a (0..15); mm: 0 full, 1 positive half (+aN), 2 negative half (-aN), 3 full inverted (aN~)
//   10hhmmmm  hat h (0..3), mask m (1 up 2 right 4 down 8 left)
typedef struct {
    uint8_t btn[NV_PAD_N_BUTTONS - 2];   // A .. TOUCHPAD (LT/RT digital bits are derived)
    uint8_t axis[NV_PAD_N_AXES];
} nv_pad_map_t;

// Bus numbers as in SDL GUIDs.
enum { NV_PAD_BUS_USB = 0x03, NV_PAD_BUS_BT = 0x05 };

// Mapping for a device: /sdcard/data/pads.txt first, then the compiled DB (by bus, VID, PID with
// the platform ordering described in tools/gen_paddb.py), else a heuristic built from what the
// device has (the Linux ABS code of each raw axis, hat and button counts). Returns true when it
// came from a DB line (info.mapped). HID drivers call nv_hid_pad_map() (nv_hid_gamepad.h).
bool nv_pad_map_lookup(uint8_t bus, uint16_t vid, uint16_t pid, const uint8_t *axis_codes,
                       uint8_t n_axes, uint8_t n_hats, uint8_t n_buttons, nv_pad_map_t *out);
// Parse one SDL mapping string ("a:b0,b:b1,leftx:a0,...", GUID and name already stripped or not).
bool nv_pad_map_parse(const char *mapping, nv_pad_map_t *out);
void nv_pad_map_apply(const nv_pad_map_t *m, const nv_hid_raw_t *raw, nv_pad_input_t *out);

#ifdef __cplusplus
}
#endif
