#!/bin/bash
# deps.sh — third-party libraries the ScummVM port links, cross-built for wasm32-wasip1 (inside WSL)
# into ~/svm/prefix: libogg + Tremor (integer Ogg Vorbis decoder: the P4 has no double FPU) for .ogg
# speech/music, libmad (fixed point) for .mp3. Idempotent; pinned tarballs/commits, sha256-checked.
set -euo pipefail
WASI="${WASI:-/opt/wasi-sdk-34.0-x86_64-linux}"
P="$HOME/svm/prefix"
S="$HOME/svm/deps"
mkdir -p "$P/include" "$P/lib" "$S"
cd "$S"
CC="$WASI/bin/wasm32-wasip1-clang"
AR="$WASI/bin/llvm-ar"
CFLAGS="-O2 -DNDEBUG -Wno-everything"

get() {   # url file sha256
    [ -f "$2" ] || curl -sSfL -o "$2" "$1"
    echo "$3  $2" | sha256sum -c --quiet -
}

build_lib() {   # name outdir srcs... (objects into a static lib)
    local name="$1" inc="$2"; shift 2
    local objs=()
    for f in "$@"; do
        local o="$S/obj-$name-$(basename "${f%.c}").o"
        "$CC" $CFLAGS -I"$inc" -I"$P/include" -c "$f" -o "$o"
        objs+=("$o")
    done
    rm -f "$P/lib/lib$name.a"
    "$AR" rcs "$P/lib/lib$name.a" "${objs[@]}"
    echo "lib$name.a"
}

# libogg 1.3.5
get https://downloads.xiph.org/releases/ogg/libogg-1.3.5.tar.gz libogg-1.3.5.tar.gz \
    0eb4b4b9420a0f51db142ba3f9c64b333f826532dc0f48c6410ae51f4799b664
if [ ! -f "$P/lib/libogg.a" ]; then
    tar xzf libogg-1.3.5.tar.gz
    mkdir -p "$P/include/ogg"
    cp libogg-1.3.5/include/ogg/ogg.h "$P/include/ogg/"
    # config_types.h is generated by configure: fixed-size types straight from stdint.
    cat > "$P/include/ogg/config_types.h" <<'EOF'
#ifndef __CONFIG_TYPES_H__
#define __CONFIG_TYPES_H__
#include <stdint.h>
typedef int16_t ogg_int16_t;
typedef uint16_t ogg_uint16_t;
typedef int32_t ogg_int32_t;
typedef uint32_t ogg_uint32_t;
typedef int64_t ogg_int64_t;
typedef uint64_t ogg_uint64_t;
#endif
EOF
    cp libogg-1.3.5/include/ogg/os_types.h "$P/include/ogg/"
    build_lib ogg libogg-1.3.5/include libogg-1.3.5/src/bitwise.c libogg-1.3.5/src/framing.c
fi

# Tremor (libvorbisidec), xiph/tremor at a pinned commit
TREMOR=820fb3237ea81af44c9cc468c8b4e20128e3e5ad
get "https://gitlab.xiph.org/xiph/tremor/-/archive/$TREMOR/tremor-$TREMOR.tar.gz" "tremor-$TREMOR.tar.gz" \
    3974455fe776a41615f60e05c85733c1bb78bff310794cbb0236f8af4b44f583
if [ ! -f "$P/lib/libvorbisidec.a" ]; then
    tar xzf "tremor-$TREMOR.tar.gz"
    T="tremor-$TREMOR"
    mkdir -p "$P/include/tremor"
    cp "$T"/ivorbiscodec.h "$T"/ivorbisfile.h "$P/include/tremor/"
    build_lib vorbisidec "$T" "$T"/mdct.c "$T"/block.c "$T"/window.c "$T"/synthesis.c "$T"/info.c \
        "$T"/floor1.c "$T"/floor0.c "$T"/vorbisfile.c "$T"/res012.c "$T"/mapping0.c "$T"/registry.c \
        "$T"/codebook.c "$T"/sharedbook.c
fi

# libmad 0.15.1b (fixed point, no asm)
get https://downloads.sourceforge.net/project/mad/libmad/0.15.1b/libmad-0.15.1b.tar.gz libmad-0.15.1b.tar.gz \
    bbfac3ed6bfbc2823d3775ebb931087371e142bb0e9bb1bee51a76a6e0078690
if [ ! -f "$P/lib/libmad.a" ]; then
    tar xzf libmad-0.15.1b.tar.gz
    M=libmad-0.15.1b
    printf '#define FPM_DEFAULT 1\n#define SIZEOF_INT 4\n#define SIZEOF_LONG 4\n#define SIZEOF_LONG_LONG 8\n' > "$M/config.h"
    CFLAGS="$CFLAGS -DHAVE_CONFIG_H -DFPM_DEFAULT" build_lib mad "$M" "$M"/version.c "$M"/fixed.c \
        "$M"/bit.c "$M"/timer.c "$M"/stream.c "$M"/frame.c "$M"/synth.c "$M"/decoder.c "$M"/layer12.c \
        "$M"/layer3.c "$M"/huffman.c
    # mad.h is generated from the per-file headers by the Makefile (minimad style): build it the same way.
    ( cd "$M" && { echo "#ifdef __cplusplus"; echo 'extern "C" {'; echo "#endif";
                   echo "# define FPM_DEFAULT"; echo "# define SIZEOF_INT 4"; echo "# define SIZEOF_LONG 4";
                   echo "# define SIZEOF_LONG_LONG 8";
                   for h in version fixed bit timer stream frame synth decoder; do
                       sed -e '/^# *include "/d' "$h.h"; done;
                   echo "#ifdef __cplusplus"; echo "}"; echo "#endif"; } > "$P/include/mad.h" )
fi
# zlib 1.3.1: streaming inflate for zip members (the built-in fallback inflates a whole member in
# memory: sky.dsk is 72 MB, the app has 8) and compressed saves.
get https://zlib.net/fossils/zlib-1.3.1.tar.gz zlib-1.3.1.tar.gz \
    9a93b2b7dfdac77ceba5a558a580e74667dd6fede4585b91eefb60f03b72df23
if [ ! -f "$P/lib/libz.a" ]; then
    tar xzf zlib-1.3.1.tar.gz
    Z=zlib-1.3.1
    cp "$Z"/zlib.h "$Z"/zconf.h "$P/include/"
    CFLAGS="$CFLAGS -DHAVE_UNISTD_H" build_lib z "$Z" "$Z"/adler32.c "$Z"/crc32.c "$Z"/deflate.c "$Z"/infback.c \
        "$Z"/inffast.c "$Z"/inflate.c "$Z"/inftrees.c "$Z"/trees.c "$Z"/zutil.c "$Z"/compress.c \
        "$Z"/uncompr.c "$Z"/gzclose.c "$Z"/gzlib.c "$Z"/gzread.c "$Z"/gzwrite.c
fi
ls -la "$P/lib"
