#!/bin/bash
# build.sh — the Lua App engine (apps/luaapp): Lua 5.4.9 as a WASI reactor ("run") with a software
# renderer, Montserrat text, the nv/gfx/ui/json/love libraries and the bundle loader.
#
#   bash ports/luaapp/build.sh [engine] [test]      (Git Bash on Windows; default: engine)
#     engine   apps/luaapp/{app.wasm,app.aot,icon.z}
#     test     PC run under WAMR (ports/luaapp/host): every lua/*/ app + the launcher, headless,
#              screenshots in ports/_src/luaapp/test/*.png
#
# Needs what ports/build.sh needs: LLVM clang (wasm32), wasi-sdk 34 sysroot + builtins, WSL
# (Ubuntu-24.04) with wamrc and gcc, Python 3 + Pillow. Lua comes from ports/fetch.sh (pinned).
set -euo pipefail
here="$(cygpath -m "$(cd "$(dirname "$0")" && pwd)")"
root="$(cygpath -m "$(cd "$here/../.." && pwd)")"
bash "$root/ports/fetch.sh" >/dev/null

CLANG="${CLANG:-/c/Program Files/LLVM/bin/clang.exe}"
WASI="${WASI:-D:/esp/wasi-sdk-34}"
SYSROOT="$WASI/wasi-sysroot-34.0"
BUILTINS="$WASI/libclang_rt-34.0/wasm32-unknown-wasip1/libclang_rt.builtins.a"
WAMRC="${WAMRC:-/root/wamrc-build/wamrc}"
DISTRO="${DISTRO:-Ubuntu-24.04}"
LUA="$root/ports/_src/lua-5.4.9/src"
GEN="$here/gen"
TEST="$root/ports/_src/luaapp/test"
mkdir -p "$GEN" "$TEST"

wsl_path() { echo "/mnt/$(echo "${1:0:1}" | tr 'A-Z' 'a-z')${1:2}"; }
wsl() { MSYS_NO_PATHCONV=1 wsl.exe -d "$DISTRO" -- "$@"; }

gen() {
    python "$here/gen_font.py" >/dev/null
    python - "$here/lib" "$GEN/lua_libs.h" <<'PY'
import os, sys
src, out = sys.argv[1], sys.argv[2]
names = sorted(n[:-4] for n in os.listdir(src) if n.endswith(".lua"))
with open(out, "w") as f:
    f.write("// generated by build.sh from lib/*.lua - do not edit\n#include <stddef.h>\n")
    for n in names:
        b = open(os.path.join(src, n + ".lua"), "rb").read()
        f.write(f"static const char lib_{n}[{len(b) + 1}] = {{")
        f.write(",".join(str(x) for x in b) + ",0};\n")
    f.write("static const struct { const char *name; const char *src; size_t len; } lua_libs[] = {\n")
    for n in names:
        f.write(f'  {{"{n}", lib_{n}, sizeof lib_{n} - 1}},\n')
    f.write(f"}};\n#define LUA_LIBS_N {len(names)}\n")
PY
}

build_engine() {
    gen
    local dir="$root/apps/luaapp" srcs=()
    mkdir -p "$dir"
    for f in "$LUA"/*.c; do case "$(basename "$f")" in lua.c|luac.c) ;; *) srcs+=("$f") ;; esac; done
    "$CLANG" --target=wasm32-wasip1 "--sysroot=$SYSROOT" -O2 -nodefaultlibs -mexec-model=reactor \
        -D_WASI_EMULATED_SIGNAL -D_WASI_EMULATED_PROCESS_CLOCKS -DLUA_COMPAT_5_3 -Wno-deprecated-declarations \
        -I"$root/ports/common" -I"$root/ports/lua/shim" -I"$root/ports/lua" -I"$LUA" -I"$here" \
        -I"$root/sdk/include" -include nv_lua_port.h \
        -Wl,--export=run -Wl,-z,stack-size=262144 -Wl,--strip-all -o "$dir/app.wasm" \
        "${srcs[@]}" "$root/ports/lua/nv_lua_glue.c" "$here/luaapp.c" "$here/gfx.c" \
        -lc -lwasi-emulated-signal -lwasi-emulated-process-clocks "$BUILTINS"
    local n; n=$(stat -c %s "$dir/app.wasm")
    [ "$n" -le 2097152 ] || { echo "app.wasm $n bytes > 2 MB device cap" >&2; exit 1; }
    echo "  luaapp/app.wasm  $n bytes"
    wsl "$WAMRC" --target=riscv32 --target-abi=ilp32f --cpu=generic-rv32 --cpu-features=+m,+a,+c,+f \
        --enable-multi-thread -o "$(wsl_path "$dir/app.aot")" "$(wsl_path "$dir/app.wasm")" >/dev/null
    n=$(stat -c %s "$dir/app.aot")
    [ "$n" -le 4194304 ] || { echo "app.aot $n bytes > 4 MB device cap" >&2; exit 1; }
    echo "  luaapp/app.aot  $n bytes"
    python "$root/tools/make_app_icon.py" --help >/dev/null 2>&1 || true
}

# PC run of the real app.wasm under the firmware's WAMR feature set (ports/host/build.sh's
# libiwasm.a): canvas, touch script and network stubs in host/luahost.c.
build_test() {
    local lib=/root/nvhost-lib2 wamr host
    wamr="$(wsl_path "$root/reference/wasm-micro-runtime")"
    host="$(wsl_path "$TEST/luahost")"
    wsl test -f "$lib/libiwasm.a" || wsl bash "$(wsl_path "$root/ports/host/build.sh")"
    wsl gcc -O2 -I"$wamr/core/iwasm/include" -o "$host" "$(wsl_path "$here/host/luahost.c")" \
        "$lib/libiwasm.a" -lm -lpthread -ldl
    python "$root/tools/lua_pack.py" test-all
}

targets=("$@")
[ ${#targets[@]} -gt 0 ] || targets=(engine)
for t in "${targets[@]}"; do echo "== $t"; "build_$t"; done
echo "done."
