"""gen_font.py - bake Montserrat Medium (SIL OFL 1.1, font/OFL.txt) into ports/luaapp/gen/font_data.h.

Anti-aliased 4-bit glyphs for the Lua App engine's text. Sizes up to 32 px carry Latin-1
(U+0020..U+00FF, enough for Italian, French, German, Spanish); the big display sizes carry ASCII
only (clock digits, titles). The engine picks the nearest size at or below the one asked for.

    python ports/luaapp/gen_font.py
"""
import os
from PIL import Image, ImageDraw, ImageFont

HERE = os.path.dirname(os.path.abspath(__file__))
TTF = os.path.join(HERE, "font", "Montserrat-Medium.ttf")
OUT = os.path.join(HERE, "gen", "font_data.h")
# beyond Latin-1: maths, arrows, typographic punctuation (all in Montserrat)
EXTRA = "πΩ∆√∞≈≠≤≥−–—…‘’“”•€←→↑↓▲▼"
SIZES = [(12, 255), (14, 255), (16, 255), (20, 255), (24, 255), (32, 255), (48, 126), (72, 126)]


def bake(size, last):
    f = ImageFont.truetype(TTF, size)
    ascent, descent = f.getmetrics()
    glyphs, bits = [], bytearray()
    for cp in range(32, last + 1):
        ch = chr(cp)
        if 127 <= cp < 160:
            glyphs.append((0, 0, 0, 0, 0, 0))
            continue
        adv = int(round(f.getlength(ch)))
        box = f.getbbox(ch, anchor="ls")          # relative to the baseline origin
        x0, y0, x1, y1 = box
        w, h = max(0, x1 - x0), max(0, y1 - y0)
        off = len(bits)
        if w and h:
            im = Image.new("L", (w, h), 0)
            ImageDraw.Draw(im).text((-x0, -y0), ch, font=f, fill=255, anchor="ls")
            px = im.tobytes()
            row = (w + 1) // 2
            for y in range(h):
                for x in range(0, w, 2):
                    a = px[y * w + x] >> 4
                    b = px[y * w + x + 1] >> 4 if x + 1 < w else 0
                    bits.append((a << 4) | b)
            assert len(bits) - off == row * h
        glyphs.append((w, h, x0, y0, adv, off))
    for ch in EXTRA:
        adv = int(round(f.getlength(ch)))
        x0, y0, x1, y1 = f.getbbox(ch, anchor="ls")
        w, h = max(0, x1 - x0), max(0, y1 - y0)
        off = len(bits)
        if w and h:
            im = Image.new("L", (w, h), 0)
            ImageDraw.Draw(im).text((-x0, -y0), ch, font=f, fill=255, anchor="ls")
            px = im.tobytes()
            for y in range(h):
                for x in range(0, w, 2):
                    a = px[y * w + x] >> 4
                    b = px[y * w + x + 1] >> 4 if x + 1 < w else 0
                    bits.append((a << 4) | b)
        glyphs.append((w, h, x0, y0, adv, off))
    return ascent, descent, last, glyphs, bits


def main():
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    out = ["// generated by gen_font.py from Montserrat Medium (SIL OFL 1.1) - do not edit",
           "#include <stdint.h>",
           "typedef struct { uint8_t w, h; int8_t x, y; uint8_t adv; uint32_t off; } lf_glyph_t;",
           "typedef struct { uint8_t size, ascent, descent; uint16_t last; const lf_glyph_t *g; const uint8_t *bits; } lf_font_t;",
           "static const uint16_t lf_extra[] = {" + ",".join(str(ord(c)) for c in EXTRA) + "};",
           f"#define LF_NEXTRA {len(EXTRA)}"]
    total = 0
    for size, last in SIZES:
        asc, desc, last, gl, bits = bake(size, last)
        total += len(bits) + len(gl) * 8
        out.append(f"static const lf_glyph_t lf_g{size}[] = {{")
        out.append(",".join(f"{{{w},{h},{x},{y},{a},{o}}}" for w, h, x, y, a, o in gl) + "};")
        out.append(f"static const uint8_t lf_b{size}[{max(1, len(bits))}] = {{")
        for i in range(0, len(bits), 40):
            out.append(",".join(str(b) for b in bits[i:i + 40]) + ",")
        out.append("};")
    out.append("static const lf_font_t lf_fonts[] = {")
    for size, last in SIZES:
        f = ImageFont.truetype(TTF, size)
        a, d = f.getmetrics()
        out.append(f"  {{{size},{a},{d},{last},lf_g{size},lf_b{size}}},")
    out.append("};")
    out.append(f"#define LF_NFONTS {len(SIZES)}")
    with open(OUT, "w") as fh:
        fh.write("\n".join(out) + "\n")
    print(f"{OUT}: {total} bytes of glyph data")


if __name__ == "__main__":
    main()
