"""embed_fonts.py <fonts dir> <out.h> <font>... — FIGlet fonts as C arrays (see nv_figlet_main.c)."""
import os
import sys

src, out, names = sys.argv[1], sys.argv[2], sys.argv[3:]
with open(out, "w", newline="\n") as f:
    f.write("// generated by ports/cli/figlet/embed_fonts.py - do not edit\n#include <stddef.h>\n")
    for i, n in enumerate(names):
        b = open(os.path.join(src, n), "rb").read()
        f.write(f"static const unsigned char nv_font{i}[{len(b)}] = {{")
        f.write(",".join(str(x) for x in b))
        f.write("};\n")
    f.write("struct nv_font { const char *file; const unsigned char *data; size_t len; };\n")
    f.write("static const struct nv_font nv_fonts[] = {\n")
    for i, n in enumerate(names):
        f.write(f'    {{ "{n}", nv_font{i}, sizeof nv_font{i} }},\n')
    f.write("};\n")
    f.write(f"#define NV_FONT_COUNT {len(names)}\n")
