// nv_figlet_main.c — FIGlet for the NucleoOS Terminal (WASI).
//
// Store packages carry no data files, so the standard fonts are compiled in (figlet_fonts.h,
// generated by ports/cli/build.sh from the release's fonts/*.flf). zipio.c is built with
// -Dfopen=nv_fig_fopen and figlet.c's existence check with stat() -> nv_fig_stat(): a real file
// wins (your own fonts, e.g. in /figlet-fonts in the SD card's home folder), otherwise a path in
// that default font folder is served from memory.
//   figlet --list   prints the built-in font names.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>

#include "figlet_fonts.h"   // struct nv_font nv_fonts[]; NV_FONT_COUNT

#define FONTDIR DEFAULTFONTDIR "/"

static const struct nv_font *builtin(const char *path) {
    if (strncmp(path, FONTDIR, strlen(FONTDIR)) != 0) return NULL;
    for (int i = 0; i < NV_FONT_COUNT; i++)
        if (!strcmp(path + strlen(FONTDIR), nv_fonts[i].file)) return &nv_fonts[i];
    return NULL;
}

FILE *nv_fig_fopen(const char *path, const char *mode) {
    FILE *f = fopen(path, mode);
    if (f || mode[0] != 'r') return f;
    const struct nv_font *b = builtin(path);
    return b ? fmemopen((void *)b->data, b->len, "rb") : NULL;
}

int nv_fig_stat(const char *path, struct stat *st) {
    if (stat(path, st) == 0) return 0;
    const struct nv_font *b = builtin(path);
    if (!b) return -1;
    memset(st, 0, sizeof *st);
    st->st_mode = S_IFREG | 0444;
    st->st_size = (off_t)b->len;
    return 0;
}

// wasi-libc has no tmpfile(); zipio only needs it for zip-compressed fonts, which then fail to
// open (the built-in fonts are plain text).
FILE *tmpfile(void) { return NULL; }

int figlet_main(int argc, char *argv[]);

int main(int argc, char *argv[]) {
    if (argc == 2 && (!strcmp(argv[1], "--list") || !strcmp(argv[1], "-list"))) {
        printf("Built-in fonts (figlet -f NAME text):\n");
        for (int i = 0; i < NV_FONT_COUNT; i++) {
            char n[64];
            snprintf(n, sizeof n, "%s", nv_fonts[i].file);
            char *dot = strrchr(n, '.');
            if (dot) *dot = '\0';
            printf("  %s\n", n);
        }
        printf("More fonts: put .flf files in %s (in the home folder) and use -f NAME.\n",
               DEFAULTFONTDIR);
        return 0;
    }
    // Fit the Terminal: default width from COLUMNS (a -w given by the user comes later and wins).
    const char *cols = getenv("COLUMNS");
    if (cols && atoi(cols) > 10 && argc < 60) {
        char *av[64];
        av[0] = argv[0];
        av[1] = "-w";
        av[2] = (char *)cols;
        for (int i = 1; i < argc; i++) av[i + 2] = argv[i];
        av[argc + 2] = NULL;
        return figlet_main(argc + 2, av);
    }
    return figlet_main(argc, argv);
}
