/* hash.h — generated by Frotz's Makefile from the 2.55 tag; fixed here. */
#ifndef VERSION
#define VERSION "2.55"
#define GIT_HASH "acf205585a9472d27c07c0fe62da4b8bc89d1ec7"
#define GIT_HASH_SHORT "acf2055"
#define GIT_DATE "2025-02-01 14:36:37 -0800"
#endif
