"""gen_names.py - build names.h (patch names 0..256 for the on-screen browser) from amy/patches.h.

    python apps/synth/gen_names.py

The OS 5x7 font only has space, 0-9, A-Z and - . : % / < > ! + x, so every name is upper-cased
and anything else is dropped. Also prints how many oscillators each patch uses per voice.
"""
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
OK = set(" 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ-.:%/<>!+")
N = 257


def main():
    src = open(os.path.join(HERE, "amy", "patches.h"), encoding="utf-8").read()
    names = {}
    oscs = {}
    for m in re.finditer(r'/\* (\d+): (.*?) \*/\s*"([^"]*)"', src):
        n = int(m.group(1))
        if n >= N or n in names:
            continue
        raw = m.group(2).strip()
        raw = raw.replace("Juno ", "JUNO ").replace("dpwe piano", "PIANO (DPWE)")
        up = raw.upper().replace("&", "+")
        up = "".join(c for c in up if c in OK)
        names[n] = re.sub(r" +", " ", up).strip()[:22]
        vs = [int(v) for v in re.findall(r"v(\d+)", m.group(3))]
        oscs[n] = max(vs) + 1 if vs else 0
    out = ["// Generated by gen_names.py from amy/patches.h - do not edit.",
           "static const char *const PATCH_NAMES[%d] = {" % N]
    for n in range(N):
        out.append('    "%s",' % names.get(n, "PATCH %d" % n))
    out.append("};")
    open(os.path.join(HERE, "names.h"), "w", newline="\n").write("\n".join(out) + "\n")
    print("names.h written; oscs/voice: juno max %d, dx7 max %d, piano %d"
          % (max(oscs[i] for i in range(128)), max(oscs[i] for i in range(128, 256)), oscs[256]))


if __name__ == "__main__":
    main()
