// Generated by ports/scummvm/gen_games.py from games.json — do not edit.
#ifndef BACKENDS_PLATFORM_NUCLEO_GAMES_H
#define BACKENDS_PLATFORM_NUCLEO_GAMES_H

struct NucleoFile { const char *url; unsigned size; const char *sha256; };
struct NucleoVariant { const char *id; const char *lang; int files[6]; };   // -1 ends
struct NucleoGame { const char *key; const char *gameid; const char *name;
                    int nvariants; const NucleoVariant *variants; };

static const NucleoFile kNucleoFiles[] = {
	{ "https://downloads.scummvm.org/frs/extras/Beneath%20a%20Steel%20Sky/bass-cd-1.2.zip", 69377781u, "53209b9400eab6fd7fa71518b2f357c8de75cfeaa5ba57024575ab79cc974593" },
	{ "https://raw.githubusercontent.com/scummvm/scummvm/v2.9.1/dists/engine-data/queen.tbl", 1100505u, "b104d1a01e3ea552b63d98da9365f6beaba40864baa74b5b53159f17fc8f1149" },
	{ "https://downloads.scummvm.org/frs/extras/Flight%20of%20the%20Amazon%20Queen/FOTAQ_Talkie-1.1.zip", 33744817u, "a25cdd5e003a0a5e402af99b218cc7ea81ad032cb36b8c05df3bd1167038d8a8" },
	{ "https://downloads.scummvm.org/frs/extras/Flight%20of%20the%20Amazon%20Queen/FOTAQ_It_Talkie_1.0.zip", 65091076u, "8d6c1a0f3bf4fbdf943e39fdb54951d3434bccc896d851ea94eedf4cc1f1e6c0" },
	{ "https://downloads.scummvm.org/frs/extras/Flight%20of%20the%20Amazon%20Queen/FOTAQ_Fr_Talkie_1.0.zip", 64531589u, "9e670686c538191a1acf3bd09ef83a11262d23247b9258ec1495b39931790543" },
	{ "https://downloads.scummvm.org/frs/extras/Flight%20of%20the%20Amazon%20Queen/FOTAQ_Ger_talkie-1.0.zip", 75938507u, "6e2826993a94864c1dd3d299369cb320a119cede4be14bf3f59b0471fa20768f" },
	{ "https://downloads.scummvm.org/frs/extras/Flight%20of%20the%20Amazon%20Queen/FOTAQ_Heb_talkie.zip", 66213122u, "18d00305642f7f426c95ff76fbf7f4a24e23d61f8144f9acdddcd0ff75f49f34" },
	{ "https://raw.githubusercontent.com/scummvm/scummvm/v2.9.1/dists/engine-data/lure.dat", 769120u, "ca07d096cf712c58f83a933fc9f36ac198fd2940c38ca4f89df370d702b3f2ff" },
	{ "https://downloads.scummvm.org/frs/extras/Lure%20of%20the%20Temptress/lure-1.1.zip", 5678861u, "f3178245a1483da1168c3a11e70b65d33c389f1f5df63d4f3a356886c1890108" },
	{ "https://downloads.scummvm.org/frs/extras/Lure%20of%20the%20Temptress/lure-it-1.1.zip", 4718011u, "524270b2fb3f1caef621acf4379e3dbb69aed3c8ec1a98b38e94b290d3b046cf" },
	{ "https://downloads.scummvm.org/frs/extras/Lure%20of%20the%20Temptress/lure-fr-1.1.zip", 3583274u, "2983149f9912a72761b1225e834a41d19aa565689b9027061a0220779694a1f8" },
	{ "https://downloads.scummvm.org/frs/extras/Lure%20of%20the%20Temptress/lure-de-1.1.zip", 3717138u, "5e83a6a8646629c55cfd84932b10231af2ff16d96e815ed0ce86564a0b3c186b" },
	{ "https://downloads.scummvm.org/frs/extras/Lure%20of%20the%20Temptress/lure-es-1.1.zip", 2176970u, "9306b9faad8c0a8189d3cbbfead511fc4d993655cc845cb8e15369baed2f7bb7" },
	{ "https://raw.githubusercontent.com/scummvm/scummvm/v2.9.1/dists/engine-data/drascula.dat", 259619u, "4ad7c24b2e642e1406fddee729159c6dfc6b1563a33bd7e421f85c4a1bd567b8" },
	{ "https://downloads.scummvm.org/frs/extras/Drascula_%20The%20Vampire%20Strikes%20Back/drascula-1.0.zip", 32842993u, "b731f6cb5a22ba8b4c3b3362f570b9a10a67b6cb0b395394b19a94b36e4e42de" },
	{ "https://downloads.scummvm.org/frs/extras/Drascula_%20The%20Vampire%20Strikes%20Back/drascula-audio-2.0.zip", 36531704u, "7e6afba36eed13dd02e0360119e9a6a8d0e7b334ddc11d7c46ab7faceb8fe401" },
	{ "https://downloads.scummvm.org/frs/extras/Drascula_%20The%20Vampire%20Strikes%20Back/drascula-int-1.1.zip", 34855203u, "24d894925c02993d0cd59013cd228b5e5c68c77d0dc57045a2aa2aba4e344388" },
	{ "https://downloads.scummvm.org/frs/extras/Dreamweb/dreamweb-uk-1.1.zip", 10198532u, "0f98e5fbeedfff5f5b904220d3bd3288da5a272f9192da03f2160c5edb8cdfb3" },
	{ "https://downloads.scummvm.org/frs/extras/Dreamweb/dreamweb-cd-it-1.1.zip", 225726238u, "7363d5f6b5aa380862d185980f50e7ac7c661cccdc3f1132f525d92bf4c47f51" },
	{ "https://downloads.scummvm.org/frs/extras/Dreamweb/dreamweb-cd-fr-1.1.zip", 166468360u, "76fff0ba67f5bcf2dde9c3fb3f5d3d5c017bb0e7368d98d9deee83d1b4182d54" },
	{ "https://downloads.scummvm.org/frs/extras/Dreamweb/dreamweb-cd-de-1.1.zip", 243874867u, "2d42fbf5dd3a58ea98ebb5c9bb33f3d5b70e92a936013248f67c33f1b82ac74b" },
	{ "https://downloads.scummvm.org/frs/extras/Dreamweb/dreamweb-cd-es-1.1.zip", 171154186u, "1f10045952d2348d2775c05c0b95ff4f35c60d6e9be109893157ef63d4444803" },
	{ "https://downloads.scummvm.org/frs/extras/Dreamweb/dreamweb-cd-uk-1.1.zip", 226067188u, "4a6f13911ce67d62c526e41048ec067b279f1b378c9210f39e0ce8d3f2b80142" },
	{ "https://downloads.scummvm.org/frs/extras/Soltys/soltys-en-v1.0.zip", 3484518u, "87b89e654b8a5b8ebe342cb4c5c6049ab9a43a5efb474d9c49bafb77dcce48f6" },
	{ "https://downloads.scummvm.org/frs/extras/Soltys/soltys-pl-v1.0.zip", 3483638u, "c865520e3752183cf5f0d062712b40dc21efc602eaa4c88952906b61979c81a7" },
	{ "https://downloads.scummvm.org/frs/extras/Soltys/soltys-es-v1.0.zip", 3527349u, "913db60d16a3c7faa2f8d02a09ea925792614bfebdc46c6df8f89ac277a35302" },
	{ "https://downloads.scummvm.org/frs/extras/Soltys/soltys-de-v1.0.zip", 3519700u, "d8a443d1252da923431a8bbe34a0432a394ee5d78e08376dda7376bac6166aa9" },
	{ "https://downloads.scummvm.org/frs/extras/Sfinx/sfinx-en-v1.1.zip", 16549117u, "f516b30a046526f78cbc923d8f907d267ab964ccd9b770afc72350e8d467ec4d" },
	{ "https://downloads.scummvm.org/frs/extras/Sfinx/sfinx-pl-v1.1.zip", 16549402u, "4111fd1a1ec3ee037b867f30827b7df58091286b7635407ca17286ac3d40472c" },
	{ "https://downloads.scummvm.org/frs/extras/Nippon%20Safes/nippon-1.0.zip", 1977894u, "53e7e2c60065e4aed193169bbcdcfd1113fa68d3efe1c8240ba073c0e20d613f" },
};
static const NucleoVariant kVariants_sky[] = {
	{ "en", "gb", { 0, -1, -1, -1, -1, -1 } },
	{ "it", "it", { 0, -1, -1, -1, -1, -1 } },
	{ "fr", "fr", { 0, -1, -1, -1, -1, -1 } },
	{ "de", "de", { 0, -1, -1, -1, -1, -1 } },
	{ "es", "es", { 0, -1, -1, -1, -1, -1 } },
	{ "pt", "br", { 0, -1, -1, -1, -1, -1 } },
};
static const NucleoVariant kVariants_queen[] = {
	{ "en", "en", { 2, 1, -1, -1, -1, -1 } },
	{ "it", "it", { 3, 1, -1, -1, -1, -1 } },
	{ "fr", "fr", { 4, 1, -1, -1, -1, -1 } },
	{ "de", "de", { 5, 1, -1, -1, -1, -1 } },
	{ "he", "he", { 6, 1, -1, -1, -1, -1 } },
};
static const NucleoVariant kVariants_lure[] = {
	{ "en", "en", { 8, 7, -1, -1, -1, -1 } },
	{ "it", "it", { 9, 7, -1, -1, -1, -1 } },
	{ "fr", "fr", { 10, 7, -1, -1, -1, -1 } },
	{ "de", "de", { 11, 7, -1, -1, -1, -1 } },
	{ "es", "es", { 12, 7, -1, -1, -1, -1 } },
};
static const NucleoVariant kVariants_drascula[] = {
	{ "en", "en", { 14, 15, 13, -1, -1, -1 } },
	{ "it", "it", { 14, 16, 15, 13, -1, -1 } },
	{ "es", "es", { 14, 16, 15, 13, -1, -1 } },
	{ "fr", "fr", { 14, 16, 15, 13, -1, -1 } },
	{ "de", "de", { 14, 16, 15, 13, -1, -1 } },
};
static const NucleoVariant kVariants_dreamweb[] = {
	{ "en", "", { 17, -1, -1, -1, -1, -1 } },
	{ "it", "", { 18, -1, -1, -1, -1, -1 } },
	{ "fr", "", { 19, -1, -1, -1, -1, -1 } },
	{ "de", "", { 20, -1, -1, -1, -1, -1 } },
	{ "es", "", { 21, -1, -1, -1, -1, -1 } },
	{ "encd", "", { 22, -1, -1, -1, -1, -1 } },
};
static const NucleoVariant kVariants_soltys[] = {
	{ "en", "en", { 23, -1, -1, -1, -1, -1 } },
	{ "pl", "pl", { 24, -1, -1, -1, -1, -1 } },
	{ "es", "es", { 25, -1, -1, -1, -1, -1 } },
	{ "de", "de", { 26, -1, -1, -1, -1, -1 } },
};
static const NucleoVariant kVariants_sfinx[] = {
	{ "en", "en", { 27, -1, -1, -1, -1, -1 } },
	{ "pl", "pl", { 28, -1, -1, -1, -1, -1 } },
};
static const NucleoVariant kVariants_nippon[] = {
	{ "multi", "", { 29, -1, -1, -1, -1, -1 } },
};
static const NucleoGame kNucleoGames[] = {
	{ "sky", "sky", "Beneath a Steel Sky", 6, kVariants_sky },
	{ "queen", "queen", "Flight of the Amazon Queen", 5, kVariants_queen },
	{ "lure", "lure", "Lure of the Temptress", 5, kVariants_lure },
	{ "drascula", "drascula", "Drascula: The Vampire Strikes Back", 5, kVariants_drascula },
	{ "dreamweb", "dreamweb", "DreamWeb", 6, kVariants_dreamweb },
	{ "soltys", "soltys", "Soltys", 4, kVariants_soltys },
	{ "sfinx", "sfinx", "Sfinx", 2, kVariants_sfinx },
	{ "nippon", "nippon", "Nippon Safes, Inc.", 1, kVariants_nippon },
};

#endif
